# swespine_full_analysis.R
# =====================================================================
# Swespine Cervical Registry — Comprehensive Federated Analysis
#
# This script uses ALL available variables from the full dataset
# produced by random_dataset_generator.R. It demonstrates the complete
# range of fedstats methods on a realistic multi-variable analysis.
#
# SCRIPT CONTRACT  (required by the coordinator GUI)
# ------------------------------------------------------------------
# 1. ANALYSIS_TITLE  — shown in the GUI header
# 2. VARS_SPEC       — all expected variables for pre-analysis validation
# 3. servers         — injected by GUI; standalone fallback below
# 4. register_output(name, value, type, caption)  — one call per result
#
# STANDALONE TESTING (no GUI required):
#
#   Remote sites:
#     FED_SITE_URLS="http://100.x.x.x:8001,http://100.x.x.x:8002" \
#       Rscript swespine_full_analysis.R
#
#   Local CSV files (data/*.csv are generated by random_dataset_generator.R):
#     Rscript swespine_full_analysis.R
# =====================================================================

library(fedstats)

# ---- Analysis identity ----
ANALYSIS_TITLE <- "Swespine Cervical — Comprehensive Analysis (Full Variables)"

# ---- Variable specification for pre-analysis validation ----
# All 48 derived variables are listed. Remove entries you don't need.
VARS_SPEC <- list(

  # --- Demographics ---
  age    = list(type = "numeric", min = 18,  max = 100),
  sexM   = list(type = "binary"),
  bmi    = list(type = "numeric", min = 10,  max = 80),
  smoker = list(type = "binary"),

  # --- Diagnosis ---
  diag_grp  = list(type = "categorical", levels = c("radiculopathy", "myelopathy")),
  diag_myelo = list(type = "binary"),

  # --- Pre-operative clinical ---
  asa    = list(type = "numeric", min = 1, max = 5),
  nurick = list(type = "numeric", min = 0, max = 5),

  # --- Comorbidities ---
  comorbid_cardiac      = list(type = "binary"),
  comorbid_neuro        = list(type = "binary"),
  comorbid_gait         = list(type = "binary"),
  comorbid_pain         = list(type = "binary"),
  opioids_preop         = list(type = "binary"),
  neuropathic_preop     = list(type = "binary"),

  # --- Work status ---
  unemployed_preop      = list(type = "binary"),
  sick_leave_preop      = list(type = "binary"),
  work_incapacity_preop = list(type = "binary"),

  # --- Pre-op PROMs ---
  nrs_arm_preop          = list(type = "numeric", min = 0,  max = 10),
  nrs_neck_preop         = list(type = "numeric", min = 0,  max = 10),
  eq5d_index_preop       = list(type = "numeric", min = -1, max = 1),
  eq5d_vas_preop         = list(type = "numeric", min = 0,  max = 100),
  ndi_index_preop        = list(type = "numeric", min = 0,  max = 100),
  myelopathy_index_preop = list(type = "numeric", min = 0,  max = 18),
  pmjoa_index_preop      = list(type = "numeric", min = 0,  max = 18),

  # --- Outcomes: 12 months ---
  nrs_arm_12m            = list(type = "numeric", min = 0,  max = 10),
  nrs_neck_12m           = list(type = "numeric", min = 0,  max = 10),
  eq5d_index_12m         = list(type = "numeric", min = -1, max = 1),
  eq5d_vas_12m           = list(type = "numeric", min = 0,  max = 100),
  ndi_index_12m          = list(type = "numeric", min = 0,  max = 100),
  myelopathy_index_12m   = list(type = "numeric", min = 0,  max = 18),
  pmjoa_index_12m        = list(type = "numeric", min = 0,  max = 18),
  patient_satisfied_12m  = list(type = "binary"),

  # --- Change scores (12 months) ---
  delta_nrs_arm_12m  = list(type = "numeric", min = -10, max = 10),
  delta_nrs_neck_12m = list(type = "numeric", min = -10, max = 10),
  delta_eq5d_12m     = list(type = "numeric", min = -2,  max = 2),
  delta_ndi_12m      = list(type = "numeric", min = -100, max = 100),

  # --- MCID outcomes (12 months) ---
  mcid_arm_12m  = list(type = "binary"),
  mcid_neck_12m = list(type = "binary"),
  mcid_eq5d_12m = list(type = "binary"),
  mcid_ndi_12m  = list(type = "binary"),

  # --- Outcomes: 24 months ---
  nrs_arm_24m    = list(type = "numeric", min = 0,  max = 10),
  nrs_neck_24m   = list(type = "numeric", min = 0,  max = 10),
  eq5d_index_24m = list(type = "numeric", min = -1, max = 1),
  ndi_index_24m  = list(type = "numeric", min = 0,  max = 100),
  mcid_arm_24m   = list(type = "binary"),

  # --- Surgical outcomes ---
  any_complication = list(type = "binary"),
  reoperated       = list(type = "binary")
)

# =====================================================================
# Standalone fallback — skipped when GUI injects `servers`
# =====================================================================
if (!exists("servers", inherits = FALSE)) {

  .site_urls_env <- Sys.getenv("FED_SITE_URLS", unset = "")
  .token_env     <- Sys.getenv("FED_API_TOKEN",  unset = "")

  if (nzchar(.site_urls_env)) {
    .urls <- trimws(strsplit(.site_urls_env, ",")[[1]])
    .urls <- .urls[nzchar(.urls)]
    if (length(.urls) == 0)
      stop("FED_SITE_URLS is set but contains no valid URLs.")
    cat("=====================================================\n")
    cat(" swespine_full_analysis.R — REMOTE MODE\n")
    cat("=====================================================\n")
    for (.u in .urls) cat(sprintf("  Site: %s\n", .u))
    cat("\n")
    servers <- lapply(.urls, function(u)
      create_remote_server(u, token = if (nzchar(.token_env)) .token_env else NULL))
  } else {
    .csv_dir   <- file.path(getwd(), "data")
    .csv_files <- if (dir.exists(.csv_dir))
      sort(list.files(.csv_dir, pattern = "[.]csv$", full.names = TRUE)) else character(0)
    if (length(.csv_files) == 0)
      stop(
        "No sites configured.\n",
        "  Option A: FED_SITE_URLS=\"http://host:port,...\" Rscript swespine_full_analysis.R\n",
        "  Option B: place CSV files in ./data/  (run random_dataset_generator.R first)\n"
      )
    cat("=====================================================\n")
    cat(" swespine_full_analysis.R — LOCAL CSV MODE\n")
    cat("=====================================================\n")
    servers <- lapply(.csv_files, function(f) {
      cat(sprintf("  Loading: %s\n", basename(f)))
      create_server(f)
    })
    cat(sprintf("  Sites loaded: %d\n\n", length(servers)))
  }
}

# =====================================================================
# Reset output registry
# =====================================================================
clear_outputs()

# =====================================================================
# 1.  Pre-analysis validation
# =====================================================================
cat("----- Data validation -----\n")

validation <- fed_validate(
  servers,
  VARS_SPEC,
  formula = mcid_arm_12m ~ age + sexM + bmi + nrs_arm_preop,
  min_n   = 30L
)
print_validation_report(validation)

.val_lines <- c(
  sprintf("Sites checked : %d", length(validation$site_reports)),
  sprintf("Status        : %s", if (validation$ok) "PASS" else "FAIL"),
  ""
)
if (length(validation$errors)   > 0)
  .val_lines <- c(.val_lines, "ERRORS:",   paste0("  ", validation$errors),   "")
if (length(validation$warnings) > 0)
  .val_lines <- c(.val_lines, "WARNINGS:", paste0("  ", validation$warnings), "")
if (length(validation$heterogeneity) > 0) {
  .val_lines <- c(.val_lines, sprintf("Heterogeneity (I²) across %d sites:",
                                      length(validation$site_reports)))
  for (.v in names(validation$heterogeneity)) {
    .h <- validation$heterogeneity[[.v]]
    .val_lines <- c(.val_lines,
                    sprintf("  %-25s I² = %5.1f%%  (pooled mean = %.3f)",
                            paste0(.v, ":"), .h$i2, .h$pooled_mean))
  }
}

register_output("Validation", paste(.val_lines, collapse = "\n"), "text",
                "Pre-analysis data validation — all sites")

# =====================================================================
# 2.  Comprehensive descriptive statistics (Table 1)
# =====================================================================
cat("\n----- Comprehensive descriptive statistics -----\n")

.fmt_ms <- function(s) sprintf("%.2f (%.2f)", s$mean, s$sd)
.fmt_pct <- function(s) sprintf("%.0f / %d (%.1f%%)", s$sum, s$n, 100 * s$mean)

# Continuous
.s_age      <- fed_numeric(servers, "age")
.s_bmi      <- fed_numeric(servers, "bmi")
.s_nrs_arm  <- fed_numeric(servers, "nrs_arm_preop")
.s_nrs_neck <- fed_numeric(servers, "nrs_neck_preop")
.s_eq5d     <- fed_numeric(servers, "eq5d_index_preop")
.s_eq5d_vas <- fed_numeric(servers, "eq5d_vas_preop")
.s_ndi      <- fed_numeric(servers, "ndi_index_preop")

# Binary
.s_sexM     <- fed_numeric(servers, "sexM")
.s_smoker   <- fed_numeric(servers, "smoker")
.s_cardiac  <- fed_numeric(servers, "comorbid_cardiac")
.s_neuro    <- fed_numeric(servers, "comorbid_neuro")
.s_opioids  <- fed_numeric(servers, "opioids_preop")
.s_sick     <- fed_numeric(servers, "sick_leave_preop")
.s_compl    <- fed_numeric(servers, "any_complication")
.s_reop     <- fed_numeric(servers, "reoperated")

desc_tab <- data.frame(
  Variable = c(
    "Age (years)",
    "BMI (kg/m²)",
    "Sex: male",
    "Smoker",
    "Comorbidity: cardiac",
    "Comorbidity: neurological",
    "Opioid use preop",
    "Sick leave preop",
    "NRS arm — preop",
    "NRS neck — preop",
    "EQ-5D index — preop",
    "EQ-5D VAS — preop",
    "NDI index — preop",
    "Any surgical complication",
    "Reoperated"
  ),
  N = c(
    .s_age$n,  .s_bmi$n,    .s_sexM$n,    .s_smoker$n,
    .s_cardiac$n, .s_neuro$n, .s_opioids$n, .s_sick$n,
    .s_nrs_arm$n, .s_nrs_neck$n, .s_eq5d$n, .s_eq5d_vas$n, .s_ndi$n,
    .s_compl$n, .s_reop$n
  ),
  "Mean (SD) / n (%)" = c(
    .fmt_ms(.s_age),  .fmt_ms(.s_bmi),
    .fmt_pct(.s_sexM), .fmt_pct(.s_smoker),
    .fmt_pct(.s_cardiac), .fmt_pct(.s_neuro),
    .fmt_pct(.s_opioids), .fmt_pct(.s_sick),
    .fmt_ms(.s_nrs_arm), .fmt_ms(.s_nrs_neck),
    .fmt_ms(.s_eq5d),    .fmt_ms(.s_eq5d_vas), .fmt_ms(.s_ndi),
    .fmt_pct(.s_compl), .fmt_pct(.s_reop)
  ),
  check.names = FALSE, stringsAsFactors = FALSE
)

register_output("Table 1 — Baseline", desc_tab, "table",
                "Baseline characteristics — pooled across all sites")

# =====================================================================
# 3.  12-month outcome summary
# =====================================================================
cat("\n----- 12-month outcomes -----\n")

.s_nrs12   <- fed_numeric(servers, "nrs_arm_12m")
.s_nneck12 <- fed_numeric(servers, "nrs_neck_12m")
.s_eq5d12  <- fed_numeric(servers, "eq5d_index_12m")
.s_vas12   <- fed_numeric(servers, "eq5d_vas_12m")
.s_ndi12   <- fed_numeric(servers, "ndi_index_12m")
.s_sat12   <- fed_numeric(servers, "patient_satisfied_12m")

.s_dnrs  <- fed_numeric(servers, "delta_nrs_arm_12m")
.s_dneq  <- fed_numeric(servers, "delta_eq5d_12m")
.s_dndi  <- fed_numeric(servers, "delta_ndi_12m")

.s_mcid_arm  <- fed_numeric(servers, "mcid_arm_12m")
.s_mcid_neck <- fed_numeric(servers, "mcid_neck_12m")
.s_mcid_eq5d <- fed_numeric(servers, "mcid_eq5d_12m")
.s_mcid_ndi  <- fed_numeric(servers, "mcid_ndi_12m")

outcome_tab <- data.frame(
  Outcome = c(
    "NRS arm (12 m)",
    "NRS neck (12 m)",
    "EQ-5D index (12 m)",
    "EQ-5D VAS (12 m)",
    "NDI index (12 m)",
    "Change NRS arm (Δ)",
    "Change EQ-5D (Δ)",
    "Change NDI (Δ)",
    "MCID arm (≥ 3 points NRS)",
    "MCID neck (≥ 3 points NRS)",
    "MCID EQ-5D (≥ 0.07)",
    "MCID NDI (≥ 10 points)",
    "Patient satisfied"
  ),
  N = c(
    .s_nrs12$n, .s_nneck12$n, .s_eq5d12$n, .s_vas12$n, .s_ndi12$n,
    .s_dnrs$n, .s_dneq$n, .s_dndi$n,
    .s_mcid_arm$n, .s_mcid_neck$n, .s_mcid_eq5d$n, .s_mcid_ndi$n,
    .s_sat12$n
  ),
  "Mean (SD) / n (%)" = c(
    .fmt_ms(.s_nrs12), .fmt_ms(.s_nneck12), .fmt_ms(.s_eq5d12),
    .fmt_ms(.s_vas12), .fmt_ms(.s_ndi12),
    .fmt_ms(.s_dnrs),  .fmt_ms(.s_dneq),    .fmt_ms(.s_dndi),
    .fmt_pct(.s_mcid_arm), .fmt_pct(.s_mcid_neck),
    .fmt_pct(.s_mcid_eq5d), .fmt_pct(.s_mcid_ndi),
    .fmt_pct(.s_sat12)
  ),
  check.names = FALSE, stringsAsFactors = FALSE
)

register_output("Table 2 — 12-month outcomes", outcome_tab, "table",
                "12-month outcome measures — pooled across all sites")

# =====================================================================
# 4.  Welch t-tests: outcomes by diagnosis
# =====================================================================
cat("\n----- Outcomes by diagnosis (Welch t-tests) -----\n")

.ttests <- list(
  list(var = "nrs_arm_preop",  label = "NRS arm preop"),
  list(var = "nrs_arm_12m",    label = "NRS arm 12m"),
  list(var = "eq5d_index_preop", label = "EQ-5D preop"),
  list(var = "eq5d_index_12m",   label = "EQ-5D 12m"),
  list(var = "ndi_index_preop",  label = "NDI preop"),
  list(var = "ndi_index_12m",    label = "NDI 12m"),
  list(var = "age",              label = "Age"),
  list(var = "bmi",              label = "BMI")
)

ttest_rows <- lapply(.ttests, function(item) {
  tt <- fed_welch_t(servers, item$var, "diag_grp",
                    "radiculopathy", "myelopathy")
  data.frame(
    Outcome        = item$label,
    "Radiculopathy (mean±SD)" = sprintf("%.2f ± %.2f (n=%d)",
                                         tt$mean1, tt$sd1, tt$n1),
    "Myelopathy (mean±SD)"    = sprintf("%.2f ± %.2f (n=%d)",
                                         tt$mean2, tt$sd2, tt$n2),
    t      = round(tt$t,  3),
    df     = round(tt$df, 1),
    p      = round(tt$p,  4),
    check.names = FALSE, stringsAsFactors = FALSE
  )
})

ttest_tab <- do.call(rbind, ttest_rows)
register_output("Table 3 — By diagnosis", ttest_tab, "table",
                "Welch t-test comparison of continuous outcomes by diagnosis group")

# =====================================================================
# 5.  Chi-square tests: binary outcomes by diagnosis
# =====================================================================
cat("\n----- Chi-square: binary outcomes by diagnosis -----\n")

.chisq_items <- list(
  list(x = "sexM",               label = "Male sex"),
  list(x = "smoker",             label = "Smoker"),
  list(x = "comorbid_cardiac",   label = "Cardiac comorbidity"),
  list(x = "opioids_preop",      label = "Opioid use preop"),
  list(x = "mcid_arm_12m",       label = "MCID arm 12m"),
  list(x = "mcid_eq5d_12m",      label = "MCID EQ-5D 12m"),
  list(x = "patient_satisfied_12m", label = "Patient satisfied 12m"),
  list(x = "any_complication",   label = "Any complication"),
  list(x = "reoperated",         label = "Reoperated")
)

chisq_rows <- lapply(.chisq_items, function(item) {
  res <- tryCatch(
    fed_chisq_2x2(servers, item$x, "diag_myelo", correct = TRUE),
    error = function(e) NULL
  )
  if (is.null(res)) {
    return(data.frame(Variable = item$label, X2 = NA, df = NA,
                      p = NA, N = NA, stringsAsFactors = FALSE))
  }
  data.frame(
    Variable = item$label,
    X2 = round(res$statistic, 3),
    df = res$df,
    p  = round(res$p, 4),
    N  = res$N,
    stringsAsFactors = FALSE
  )
})

chisq_tab <- do.call(rbind, chisq_rows)
register_output("Table 4 — Chi-square", chisq_tab, "table",
                "Chi-square (Yates correction): binary variables by diagnosis group")

# =====================================================================
# 6.  Linear regression: 12-month NRS arm improvement
# =====================================================================
cat("\n----- Linear regression: delta_nrs_arm_12m -----\n")

lm_full <- fed_lm(
  servers,
  delta_nrs_arm_12m ~ age + sexM + bmi + smoker +
    nrs_arm_preop + eq5d_index_preop + diag_myelo +
    asa + comorbid_cardiac + opioids_preop
)

lm_tab <- data.frame(
  Term      = names(lm_full$coefficients),
  Estimate  = round(lm_full$coefficients, 4),
  Std.Error = round(lm_full$se,           4),
  t.value   = round(lm_full$t,            3),
  p.value   = round(lm_full$p,            4),
  stringsAsFactors = FALSE
)
rownames(lm_tab) <- NULL

cat(sprintf("N = %d | Residual SE = %.4f | df = %d\n",
            lm_full$N, lm_full$sigma, lm_full$df))

register_output("Table 5 — Linear regression", lm_tab, "table",
                sprintf(
                  "OLS: delta_nrs_arm_12m ~ age + sexM + bmi + smoker + nrs_arm_preop + eq5d_index_preop + diag_myelo + asa + comorbid_cardiac + opioids_preop  |  N = %d, Residual SE = %.4f",
                  lm_full$N, lm_full$sigma
                ))

# =====================================================================
# 7.  Logistic regression: patient satisfaction at 12 months
# =====================================================================
cat("\n----- Logistic regression: patient_satisfied_12m -----\n")

logit_sat <- fed_logistic_newton(
  servers,
  patient_satisfied_12m ~ age + sexM + bmi + smoker +
    nrs_arm_preop + ndi_index_preop + diag_myelo +
    comorbid_cardiac + opioids_preop + nrs_arm_12m,
  robust_cluster = TRUE,
  verbose        = FALSE
)

.se_sat <- if (!is.null(logit_sat$se_robust)) logit_sat$se_robust else logit_sat$se
.b_sat  <- logit_sat$coefficients
.z_sat  <- .b_sat / .se_sat
.p_sat  <- 2 * (1 - pnorm(abs(.z_sat)))

logit_sat_tab <- data.frame(
  Term      = names(.b_sat),
  Estimate  = round(.b_sat,                     4),
  Std.Error = round(.se_sat,                    4),
  z.value   = round(.z_sat,                     3),
  p.value   = round(.p_sat,                     4),
  OR        = round(exp(.b_sat),               4),
  CI.lower  = round(exp(.b_sat - 1.96 * .se_sat), 4),
  CI.upper  = round(exp(.b_sat + 1.96 * .se_sat), 4),
  stringsAsFactors = FALSE
)
rownames(logit_sat_tab) <- NULL

register_output("Table 6 — Logistic (satisfaction)", logit_sat_tab, "table",
                sprintf(
                  "Logistic: patient_satisfied_12m ~ 10 predictors | N = %d, logLik = %.3f%s",
                  logit_sat$N, logit_sat$logLik,
                  if (!is.null(logit_sat$clusters))
                    sprintf(", cluster-robust SE (%d sites)", logit_sat$clusters) else ""
                ))

# =====================================================================
# 8.  Logistic regression: MCID EQ-5D at 12 months
# =====================================================================
cat("\n----- Logistic regression: mcid_eq5d_12m -----\n")

logit_eq5d <- fed_logistic_newton(
  servers,
  mcid_eq5d_12m ~ age + sexM + diag_myelo +
    eq5d_index_preop + ndi_index_preop +
    smoker + opioids_preop + asa,
  robust_cluster = TRUE,
  verbose        = FALSE
)

.se_eq <- if (!is.null(logit_eq5d$se_robust)) logit_eq5d$se_robust else logit_eq5d$se
.b_eq  <- logit_eq5d$coefficients
.z_eq  <- .b_eq / .se_eq
.p_eq  <- 2 * (1 - pnorm(abs(.z_eq)))

logit_eq5d_tab <- data.frame(
  Term      = names(.b_eq),
  Estimate  = round(.b_eq,                    4),
  Std.Error = round(.se_eq,                   4),
  z.value   = round(.z_eq,                    3),
  p.value   = round(.p_eq,                    4),
  OR        = round(exp(.b_eq),              4),
  CI.lower  = round(exp(.b_eq - 1.96 * .se_eq), 4),
  CI.upper  = round(exp(.b_eq + 1.96 * .se_eq), 4),
  stringsAsFactors = FALSE
)
rownames(logit_eq5d_tab) <- NULL

register_output("Table 7 — Logistic (EQ-5D MCID)", logit_eq5d_tab, "table",
                sprintf(
                  "Logistic: mcid_eq5d_12m ~ 8 predictors | N = %d, logLik = %.3f",
                  logit_eq5d$N, logit_eq5d$logLik
                ))

# =====================================================================
# 9.  Forest plot: patient satisfaction logistic regression
# =====================================================================
register_output(
  name  = "Forest plot — Satisfaction",
  value = local({
    .lt <- logit_sat_tab
    function() {
      .rows <- .lt[.lt$Term != "(Intercept)", ]
      .n    <- nrow(.rows)
      if (.n == 0) { plot.new(); text(0.5, 0.5, "No predictors."); return() }
      .y_pos <- seq(.n, 1)
      .x_lo  <- max(0.05, min(.rows$CI.lower, na.rm = TRUE) * 0.75)
      .x_hi  <- max(.rows$CI.upper, na.rm = TRUE) * 1.40
      .old   <- par(mar = c(4.5, 10, 3.5, 2.5))
      on.exit(par(.old), add = TRUE)
      plot(.rows$OR, .y_pos,
           xlim = c(.x_lo, .x_hi), ylim = c(0.3, .n + 0.7),
           xlab = "Odds ratio (95% CI)", ylab = "",
           yaxt = "n", log = "x", pch = 15, cex = 1.4, col = "#2b6cb0",
           main = "Patient satisfaction at 12 months")
      for (.i in seq_len(.n))
        lines(c(.rows$CI.lower[.i], .rows$CI.upper[.i]),
              c(.y_pos[.i], .y_pos[.i]), col = "#2b6cb0", lwd = 2)
      abline(v = 1, lty = 2, col = "grey60")
      axis(2, at = .y_pos, labels = .rows$Term, las = 1, cex.axis = 0.85)
      for (.i in seq_len(.n))
        text(.rows$OR[.i], .y_pos[.i] + 0.38,
             labels = sprintf("%.2f [%.2f–%.2f]",
                              .rows$OR[.i], .rows$CI.lower[.i], .rows$CI.upper[.i]),
             cex = 0.72, col = "#2b6cb0")
    }
  }),
  type    = "plot",
  caption = "Odds ratios (95% CI) for patient satisfaction at 12 months — logistic regression"
)

# =====================================================================
# 10. Forest plot: EQ-5D MCID logistic regression
# =====================================================================
register_output(
  name  = "Forest plot — EQ-5D MCID",
  value = local({
    .lt <- logit_eq5d_tab
    function() {
      .rows <- .lt[.lt$Term != "(Intercept)", ]
      .n    <- nrow(.rows)
      if (.n == 0) { plot.new(); text(0.5, 0.5, "No predictors."); return() }
      .y_pos <- seq(.n, 1)
      .x_lo  <- max(0.05, min(.rows$CI.lower, na.rm = TRUE) * 0.75)
      .x_hi  <- max(.rows$CI.upper, na.rm = TRUE) * 1.40
      .old   <- par(mar = c(4.5, 10, 3.5, 2.5))
      on.exit(par(.old), add = TRUE)
      plot(.rows$OR, .y_pos,
           xlim = c(.x_lo, .x_hi), ylim = c(0.3, .n + 0.7),
           xlab = "Odds ratio (95% CI)", ylab = "",
           yaxt = "n", log = "x", pch = 15, cex = 1.4, col = "#276749",
           main = "MCID EQ-5D at 12 months")
      for (.i in seq_len(.n))
        lines(c(.rows$CI.lower[.i], .rows$CI.upper[.i]),
              c(.y_pos[.i], .y_pos[.i]), col = "#276749", lwd = 2)
      abline(v = 1, lty = 2, col = "grey60")
      axis(2, at = .y_pos, labels = .rows$Term, las = 1, cex.axis = 0.85)
      for (.i in seq_len(.n))
        text(.rows$OR[.i], .y_pos[.i] + 0.38,
             labels = sprintf("%.2f [%.2f–%.2f]",
                              .rows$OR[.i], .rows$CI.lower[.i], .rows$CI.upper[.i]),
             cex = 0.72, col = "#276749")
    }
  }),
  type    = "plot",
  caption = "Odds ratios (95% CI) for MCID EQ-5D at 12 months — logistic regression"
)

# =====================================================================
# Done
# =====================================================================
cat("\n=====================================================\n")
cat(" Analysis complete.\n")
cat(sprintf(" Outputs registered: %d\n", length(get_outputs())))
cat("=====================================================\n")
